memory/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^memory/', include('memory_project.urls', namespace='memory')),
    url(r'^admin/', include(admin.site.urls)),
)

memory_project/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_card$', views.add_card, name='add_card'),
    url(r'^add_text$', views.add_text, name='add_text'),
    url(r'^all$', views.all, name='all'),
    url(r'^all_texts$', views.all_texts, name='all_texts'),
    url(r'^(?P<card_id>[0-9]+)/card_renew$', views.card_renew, name='card_renew'),
    url(r'^(?P<card_id>[0-9]+)/card_change$', views.card_change, name='card_change'),
    url(r'^(?P<card_id>[0-9]+)/card_delete$', views.card_delete, name='card_delete'),
    url(r'^text/(?P<text_slug>[a-zA-Z0-9-]+)', views.text_show, name='text_show'),
]

memory_project/models.py
from django.db import models


class Card(models.Model):
    VALUE_CHOICES = (
        (0, '0'),
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    first_side_text = models.CharField(max_length=200)
    second_side_text = models.CharField(max_length=200)
    extra_text = models.CharField(max_length=200, blank=False, null=True)
    show_date = models.DateTimeField('show date')
    value = models.IntegerField(max_length=10, choices=VALUE_CHOICES, default=2)


class TranslateText(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    content = models.TextField()

memory_project/forms.py
from django.forms import ModelForm, Textarea
from django.utils.text import slugify
from .models import Card, TranslateText


class CardForm(ModelForm):
    class Meta:
        model = Card
        fields = ['first_side_text', 'second_side_text', 'extra_text', 'value']
        widgets = {
            'extra_text': Textarea(attrs={'cols': 40, 'rows': 5}),
        }
        labels = {
            'first_side_text': ('Question'),
            'second_side_text': ('Answer'),
            'extra_text': ('Example'),
        }


class CardChangeForm(ModelForm):
    class Meta:
        model = Card
        fields = ['first_side_text', 'second_side_text', 'extra_text']
        labels = {
            'first_side_text': ('Question'),
            'second_side_text': ('Answer'),
            'extra_text': ('Example'),
        }
        widgets = {
            'extra_text': Textarea(attrs={'cols': 40, 'rows': 5}),
        }


class TextForm(ModelForm):
    class Meta:
        model = TranslateText
        fields = ['title', 'content']
        labels = {
            'title': ('Title'),
            'content': ('Your Text'),
        }

    def save(self):
        instance = super(TextForm, self).save(commit=False)
        max_length = TranslateText._meta.get_field('slug').max_length
        instance.slug = slugify(instance.title)[:max_length]
        instance.save()
        return instance

memory_project/views.py
from datetime import datetime, timedelta
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CardForm, CardChangeForm, TextForm
from .models import Card, TranslateText


def index(request):
    context = None
    now = datetime.now()
    card_list = Card.objects.filter(show_date__lte=now)
    list_len = len(card_list)
    if list_len > 0:
        context = {'card': card_list[0], 'list_len': list_len}
    return render(request, 'memory_project/index.html', context)


def card_renew(request, card_id):
    p = get_object_or_404(Card, pk=card_id)
    val = request.POST['choice']
    if val == '1':
        num_days = 1
    elif val == '2':
        num_days = 2
    elif val == '3':
        num_days = 3
    elif val == '4':
        num_days = 7
    elif val == '5':
        num_days = 30
    else:
        num_days = 0
    p.show_date = datetime.now() + timedelta(days=num_days)
    p.value = val
    p.save()
    return HttpResponseRedirect(reverse('memory:index'))


def card_delete(request, card_id):
    p = get_object_or_404(Card, pk=card_id)
    p.delete()
    return HttpResponseRedirect(reverse('memory:index'))


def card_change(request, card_id):
    card = get_object_or_404(Card, pk=card_id)
    date = card.show_date
    value = card.value
    if request.method == 'POST':
        form = CardChangeForm(request.POST)
        if form.is_valid():
            card = form.save(commit=False)
            card.show_date = date
            card.value = value
            card.pk = card_id
            card.save()
            form.save
            return HttpResponseRedirect('/memory/')
    else:
        form = CardChangeForm(instance=card)
    return render(request, 'memory_project/card_form.html', {'form': form})


def add_card(request):
    if request.method == 'POST':
        form = CardForm(request.POST)
        if form.is_valid():
            card = form.save(commit=False)
            card.show_date = datetime.now()
            card.save()
            return HttpResponseRedirect('/memory/')
    else:
        form = CardForm()
    return render(request, 'memory_project/card_form.html', {'form': form})


def add_text(request):
    if request.method == 'POST':
        form = TextForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/memory/all_texts')
    else:
        form = TextForm()
    return render(request, 'memory_project/text_form.html', {'form': form})


def all(request):
    card_list = Card.objects.all()
    list_len = len(card_list)
    if list_len > 0:
        context = {'cards': card_list, 'list_len': list_len}
    return render(request, 'memory_project/all.html', context)


def all_texts(request):
    text_list = TranslateText.objects.all()
    paginator = Paginator(text_list, 3)
    page = request.GET.get('page')
    list_len = len(text_list)
    try:
        texts = paginator.page(page)
    except PageNotAnInteger:
        texts = paginator.page(1)
    except EmptyPage:
        texts = paginator.page(paginator.num_pages)
    return render(request, 'memory_project/all_texts.html', {'texts': texts, 'list_len': list_len})


def text_show(request, text_slug):
    text = get_object_or_404(TranslateText, slug=text_slug)
    return render(request, 'memory_project/text_show.html', {'text': text})

memory_project/templates/memory_project/all.html
{% extends "memory_project/base.html" %}


{% block contents %}
    There are <b>{{ list_len }}</b> words in your vocabulary
    <a style="float: right;" href="{% url 'memory:add_card' %}">
        <span class="glyphicon glyphicon-plus"></span>Add new word
    </a>
    <br><br>
    <table class="table table-bordered table-hover">
    <tr>
        <th>First side</th>
        <th>Second side</th>
        <th>Progress</th>
    </tr>
    {% for card in cards %}
    <tr>
        <td class="text-primary">{{ card.first_side_text }}</td>
        <td class="text-success">{{ card.second_side_text }}</td>
        <td>
            {% if card.value == 0 %}
            <div style="border: black; width: 40px; length: 100px;">
                <div></div>
            </div>
            {% elif card.value == 1 %}
            <div style="border: black; width: 100%; height: 60%; position: relative;
                border-style: solid; border-color: #000; text-align: center;">
                <div style="position: absolute; width: 100%; height: 100%;">10%</div>
                <div style="width: 10%; height: 100%; background-color: #5bc0de;">&nbsp;</div>
            </div>
            {% elif card.value == 2 %}
            <div style="border: black; width: 100%; height: 60%; position: relative;
                border-style: solid; border-color: #000; text-align: center;">
                <div style="position: absolute; width: 100%; height: 100%;">30%</div>
                <div style="width: 30%; height: 100%; background-color: #5bc0de;">&nbsp;</div>
            </div>
            {% elif card.value == 3 %}
            <div style="border: black; width: 100%; height: 60%; position: relative;
                border-style: solid; border-color: #000; text-align: center;">
                <div style="position: absolute; width: 100%; height: 100%;">50%</div>
                <div style="width: 50%; height: 100%; background-color: #5bc0de;">&nbsp;</div>
            </div>
            {% elif card.value == 4 %}
            <div style="border: black; width: 100%; height: 60%; position: relative;
                border-style: solid; border-color: #000; text-align: center;">
                <div style="position: absolute; width: 100%; height: 100%;">80%</div>
                <div style="width: 80%; height: 100%; background-color: #5bc0de;">&nbsp;</div>
            </div>
            {% elif card.value == 5 %}
            <div style="border: black; width: 100%; height: 60%; position: relative;
                border-style: solid; border-color: #000; text-align: center;">
                <div style="position: absolute; width: 100%; height: 100%;">100%</div>
                <div style="width: 100%; height: 100%; background-color: #5bc0de;">&nbsp;</div>
            </div>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </table>

{% endblock %}

memory_project/templates/memory_project/all_texts.html
{% extends "memory_project/base.html" %}


{% block contents %}
There are <b>{{ list_len }}</b> texts
<a style="float: right;" href="{% url 'memory:add_text' %}" class="text-success"><span class="glyphicon glyphicon-plus"></span>
    Add text to translate
</a>
<br><br>
<div class="list-group">
    {% for text in texts %}
    <a href="{% url 'memory:text_show' text.slug %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ text.title }}</h4>
        <p class="list-group-item-text">{{ text.content|truncatechars:500 }}...</p>
    </a>
    {% endfor %}
</div>

<nav>
    <ul class="pagination">
        {% if texts.has_previous %}
        <li>
            <a href="?page={{ texts.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li><a href="?page=1">1</a></li>
        <li><a href="#">...</a></li>
        {% endif %}
        <li class="active"><a href="#">{{ texts.number }}</a></li>
        {% if texts.has_next %}
        <li><a href="#">...</a></li>
        <li><a href="?page={{ texts.paginator.num_pages }}">{{ texts.paginator.num_pages }}</a></li>
        <li>
            <a href="?page={{ texts.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock contents %}

memory_project/templates/memory_project/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
  <body style="width:40%;align=center;margin-left:auto;margin-right:auto; padding: 0 0 50px; position: relative;">
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <a href="{% url 'memory:index' %}" style="position:relative; display: block; height: 200px; width: 100px;">
        <img src="{% static 'img/logo.png' %}"  height="200" width="300" style="position: absolute; left: -90px;">
    </a>
    {% block contents %}{% endblock %}

  </body>

memory_project/templates/memory_project/card.html
<ul style="list-style-type:none;">
    {% for card in card_list %}
    <li>
        <div style="margin-bottom: 60px;">
            <ul class="list-group">
                <li class="list-group-item" style="text-align: center;"><h3>{{ card.first_side_text }}</h3></li>
                <li class="list-group-item" style="text-align:center;"><h3>{{ card.second_side_text }}</h3></li>
                <li class="list-group-item">
                    <form action="{% url 'memory:card_renew' card.id %}" method="post">
                    {% csrf_token %}
                    <div class="btn-group btn-group-justified" role="group" aria-label="...">
                        {% for choice in card.VALUE_CHOICES %}
                        <div class="btn-group" style="text-align: center;" role="group">
                            <input type="radio" value="{{ choice.0 }}" name="choice" {% if card.value == choice.0 %} checked {% endif %}>
                                {{ choice.0 }}
                            </input>
                        </div>
                        {% endfor %}
                    </div>
                     <div class="center-block" style="text-align:center; margin:20px 0 10px 0;">
                         <input type="submit" class="btn btn-success" value="OK">
                     </div>
                    </form>
                </li>
            </ul>
            <a href="{% url 'memory:card_change' card.id %}" class="btn btn-info">Change</a>
            <a href="{% url 'memory:card_delete' card.id %}" class="btn btn-danger">Delete</a>
        </div>
    </li>
    {% endfor %}
    </ul>

memory_project/templates/memory_project/card_form.html
{% extends "memory_project/base.html" %}


{% block contents %}

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
    <form action="" method="post">
        <table class="table">
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" class="btn btn-success" value="OK">
    </form>

{% endblock %}

memory_project/templates/memory_project/index.html
{% extends "memory_project/base.html" %}


{% block contents %}
    <ul class="nav" style="position: absolute; right: 0; top: 60px;">
        <li role="presentation"><a href="{% url 'memory:add_card' %}"><span class="glyphicon glyphicon-plus"></span>
            Add a new word</a>
        </li>
        <li role="presentation"><a href="{% url 'memory:add_text' %}" class="text-success">
            <span class="glyphicon glyphicon-plus"></span> Add a text to translate</a>
        </li>
    </ul>
    <ul class="nav" style="position: absolute; right: 200px; top: 60px;">
        <li><a href="{% url 'memory:all' %}" class="text-danger">All words</a></li>
        <li role="presentation"><a href="{% url 'memory:all_texts' %}" class="text-warning">All texts</a></li>
    </ul>
    {% if card %}
    <div>
        <div style="float: right;">
            <a href="{% url 'memory:card_change' card.id %}" class="glyphicon glyphicon-pencil" title="Change"></a>
            <a href="{% url 'memory:card_delete' card.id %}" class="glyphicon glyphicon-remove text-danger" title="Delete"></a>
            <a href="{% url 'memory:add_card' %}" class="glyphicon glyphicon-plus text-success" title="Add a new word"></a>
        </div>
        <div style="clear: both; margin-bottom: 20px;"></div>
        <ul class="list-group">
            <li class="list-group-item" style="text-align: center; min-height: 150px;">
                <div style="text-align: left; margin-bottom: 30px;">Question</div>
                <h3>{{ card.first_side_text }}</h3>
            </li>
            {% if card.extra_text %}
            <li class="list-group-item" style="text-align:center; min-height: 150px;">
                <div style="text-align: left; margin-bottom: 30px;">Example</div>
                {% if request.GET.extra %}
                <b style="color: #888;">{{ card.extra_text }}</b>
                {% else %}
                <span id="show_extra_link"><p class="btn btn-info" id="show_extra">Show Example</p></span>
                {% endif %}
            </li>
            {% endif %}
            <li class="list-group-item" style="text-align:center; min-height: 150px;">
                <div style="text-align: left; margin-bottom: 30px;">Answer</div>
                {% if request.GET.answer %}
                <h3>{{ card.second_side_text }}</h3>
                {% else %}
                <span id="show_answer_link"><p class="btn btn-info"  id="show_answer">Show answer</p></span>
                {% endif %}
            </li>
            <li class="list-group-item">
                <div style="text-align: left; margin-bottom: 30px;">Grade your answer</div>
                <form action="{% url 'memory:card_renew' card.id %}" method="post" id="form">
                {% csrf_token %}
                <div class="btn-group btn-group-justified" role="group" aria-label="...">
                    {% for choice in card.VALUE_CHOICES %}
                    <div class="btn-group" style="text-align: center;" role="group">
                        <input type="submit"
                               class="btn btn-info {% if card.value == choice.0 %} btn-warning {% endif %}" value="{{ choice.0 }}"
                               id="choice{{ choice.0 }}"
                               name="choice">
                        </input>
                    </div>
                    {% endfor %}
                </div>
                </form>
            </li>
        </ul>
        <b>Words for practice today: {{ list_len }}</b>
    </div>
    {% else %}
    There is no card for practice today.
    {% endif %}

    <script>
        $(document).ready(function() {
            hr = window.location;
            $("#show_answer").on('click', function() {
                if(hr.href.indexOf("answer") == -1) {
                    if (hr.search)
                        href = hr + "&answer=show";
                    else
                        href = hr + "?answer=show";
                }
                 window.location.href = href;
            })
            $("#show_extra").on('click', function() {
                if(hr.href.indexOf("extra") == -1) {
                    if (hr.search)
                        href = hr + "&extra=show";
                    else
                        href = hr + "?extra=show";
                }
                 window.location.href = href;
            })
            $(window).keypress(function(e) {
                if (e.keyCode == 0 || e.keyCode == 32) {
                    if(hr.href.indexOf("answer") == -1) {
                        if (hr.search)
                            href = hr + "&answer=show";
                        else
                            href = hr + "?answer=show";
                    }
                    window.location.href = href;
                } else if (e.keyCode == 48) {
                    var $el = $("#choice0");
                    $el.siblings().removeClass('btn_warning');
                    $el.addClass('btn_warning');
                    $el.click();
                } else if (e.keyCode == 49) {
                    var $el = $("#choice1");
                    $el.siblings().removeClass('btn_warning');
                    $el.addClass('btn_warning');
                    $el.click();
                } else if (e.keyCode == 50) {
                    var $el = $("#choice2");
                    $el.siblings().removeClass('btn_warning');
                    $el.addClass('btn_warning');
                    $el.delay(5000).click();
                } else if (e.keyCode == 51) {
                    var $el = $("#choice3");
                    $el.siblings().removeClass('btn_warning');
                    $el.addClass('btn_warning');
                    $el.click();
                } else if (e.keyCode == 52) {
                    var $el = $("#choice4");
                    $el.siblings().removeClass('btn_warning');
                    $el.addClass('btn_warning');
                    $el.click();
                } else if (e.keyCode == 53) {
                    var $el = $("#choice5");
                    $el.siblings().removeClass('btn_warning');
                    $el.addClass('btn_warning');
                    $el.click();
                }

            })
        });
    </script>

{% endblock %}

memory_project/templates/memory_project/text_form.html
{% extends "memory_project/base.html" %}


{% block contents %}

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
    <form action="" method="post">
        <table class="table">
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" class="btn btn-success" value="OK">
    </form>

{% endblock %}

memory_project/templates/memory_project/text_show.html
{% extends "memory_project/base.html" %}


{% block contents %}
<h2>{{ text.title }}</h2>
<div>
    <p>
        {{ text.content|linebreaksbr }}
    </p>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
    <div style="position: relative;">
        <a id="g_translate" href="" style="position: absolute; left: -50px; top: 0;">
            <img src="{% static 'img/Google-Translate-icon.png' %}">
        </a>
        <form action="" method="post">
            <table class="table">
                {{ form.as_table }}
            </table>
            {% csrf_token %}
            <input type="submit" class="btn btn-success" value="OK">
        </form>
    </div>
</div>
{% endblock %}